name: cog
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit-dev=11.7
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - lightning
  - numpy=1.26
  - pip:
    - -r requirements.txt